name = input("Имя клиента: ")
business = input("Чем занимается бизнес клиента? ")
clients = input("Кто его клиенты? ")
problem = input("Какая повторяющаяся задача отнимает время? ")
if problem == "":
    print("Ошибка: проблему нельзя оставлять пустой.")
    exit()
current_process = input("Как клиент решает это сейчас? ")
deadline = input("Когда нужен результат? ")
budget = input("Какой бюджет? ")

print()
print("=== БРИФ КЛИЕНТА ===")
print("Клиент:", name)
print("Бизнес:", business)
print("Клиенты бизнеса:", clients)
print("Проблема:", problem)
print("Как решает сейчас:", current_process)
print("Срок:", deadline)
print("Бюджет:", budget)
print()
print("Идея решения:")
print("Можно сделать автоматизацию, которая сократит ручную работу в этой задаче.")
with open("brief.txt", "a", encoding="utf-8") as file:
    file.write("=== БРИФ КЛИЕНТА ===\n")
    file.write("Клиент: " + name + "\n")
    file.write("Бизнес: " + business + "\n")
    file.write("Клиенты бизнеса: " + clients + "\n")
    file.write("Проблема: " + problem + "\n")
    file.write("Как решает сейчас: " + current_process + "\n")
    file.write("Срок: " + deadline + "\n")
    file.write("Бюджет: " + budget + "\n")
    file.write("\n---\n")

print()
print("Бриф сохранен в файл brief.txt")
